global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trackly'
    static_configs:
      - targets: ['trackly:8000']  # Replace 'trackly' with your container name

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # System metrics
